package com.example.thirtydays.ui.theme

import androidx.compose.ui.graphics.Color

// Палитра Material 3: индиго (основной), сиреневый (дополнительный), розово-лиловый (акцент).
// Базовый цвет #4355B9, оттенки подобраны по схеме Tonal Spot.

val primaryLight = Color(0xFF4355B9)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDEE0FF)
val onPrimaryContainerLight = Color(0xFF00105C)
val secondaryLight = Color(0xFF5A5D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDFE1F9)
val onSecondaryContainerLight = Color(0xFF171B2C)
val tertiaryLight = Color(0xFF76546E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD7F2)
val onTertiaryContainerLight = Color(0xFF2D1228)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFEFBFF)
val onBackgroundLight = Color(0xFF1B1B1F)
val surfaceLight = Color(0xFFFEFBFF)
val onSurfaceLight = Color(0xFF1B1B1F)
val surfaceVariantLight = Color(0xFFE3E1EC)
val onSurfaceVariantLight = Color(0xFF46464F)
val outlineLight = Color(0xFF777680)
val outlineVariantLight = Color(0xFFC7C5D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303034)
val inverseOnSurfaceLight = Color(0xFFF2F0F4)
val inversePrimaryLight = Color(0xFFB8C3FF)
val surfaceDimLight = Color(0xFFDCD9DE)
val surfaceBrightLight = Color(0xFFFEFBFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF7F2FA)
val surfaceContainerLight = Color(0xFFF1EDF4)
val surfaceContainerHighLight = Color(0xFFEBE7EE)
val surfaceContainerHighestLight = Color(0xFFE5E1E9)

val primaryDark = Color(0xFFB8C3FF)
val onPrimaryDark = Color(0xFF08218A)
val primaryContainerDark = Color(0xFF293CA0)
val onPrimaryContainerDark = Color(0xFFDEE0FF)
val secondaryDark = Color(0xFFC3C5DD)
val onSecondaryDark = Color(0xFF2C2F42)
val secondaryContainerDark = Color(0xFF424559)
val onSecondaryContainerDark = Color(0xFFDFE1F9)
val tertiaryDark = Color(0xFFE6BAD7)
val onTertiaryDark = Color(0xFF44263E)
val tertiaryContainerDark = Color(0xFF5D3C55)
val onTertiaryContainerDark = Color(0xFFFFD7F2)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1B1B1F)
val onBackgroundDark = Color(0xFFE4E1E6)
val surfaceDark = Color(0xFF1B1B1F)
val onSurfaceDark = Color(0xFFE4E1E6)
val surfaceVariantDark = Color(0xFF46464F)
val onSurfaceVariantDark = Color(0xFFC7C5D0)
val outlineDark = Color(0xFF91909A)
val outlineVariantDark = Color(0xFF46464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E1E6)
val inverseOnSurfaceDark = Color(0xFF303034)
val inversePrimaryDark = Color(0xFF4355B9)
val surfaceDimDark = Color(0xFF121316)
val surfaceBrightDark = Color(0xFF38393C)
val surfaceContainerLowestDark = Color(0xFF0D0E11)
val surfaceContainerLowDark = Color(0xFF1B1B1F)
val surfaceContainerDark = Color(0xFF1F1F23)
val surfaceContainerHighDark = Color(0xFF292A2D)
val surfaceContainerHighestDark = Color(0xFF343438)
